# Find more available configuration properties on the following pages of the documentation.
# https://docs.camunda.org/manual/latest/user-guide/camunda-bpm-run/#configure-camunda-bpm-run
# https://docs.camunda.org/manual/latest/user-guide/spring-boot-integration/configuration/#camunda-engine-properties


camunda.bpm:
  generic-properties.properties:
    javaSerializationFormatEnabled: true
  admin-user:
    id: demo
    password: demo
  run:
    # https://docs.camunda.org/manual/latest/user-guide/camunda-bpm-run/#cross-origin-resource-sharing
    cors:
      enabled: true
      allowed-origins: "*"

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/myclinic?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8087